### ISSUE TITLE
Cannot get pass first npm command to install the sample.

### ISSUE THREAD

**Issue by livecano** [georgejecook/maestro-roku-sample#1]
I've been trying to run the example but it isn't working.

I get the following when executing `npm install`

``` shell
66 verbose stack TypeError: Cannot convert undefined or null to object
66 verbose stack     at Function.keys (<anonymous>)
66 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:213:22)
66 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
66 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1081:19)
66 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:950:11)
66 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
66 verbose stack     at async Promise.all (index 1)
66 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
66 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:159:5)
66 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:66:5)
67 verbose cwd /maestro-roku-sample-master
68 verbose Darwin 20.6.0
69 verbose argv "/usr/local/Cellar/node/14.10.1/bin/node" "/usr/local/bin/npm" "install"
70 verbose node v14.10.1
71 verbose npm  v8.5.5
72 error Cannot convert undefined or null to object
73 verbose exit 1
74 timing npm Completed in 3562ms
75 verbose unfinished npm timer reify 1648841858457
76 verbose unfinished npm timer reify:loadTrees 1648841858468
77 verbose code 1
```

**Comment by guirkgumbo** [comment]
@livecano @dacianroman 
Also stuck here. Did you do anything in particular to resolve this?
